image: us.gcr.io/tools-203611/gitlab-base:28

services:
  - postgres

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"

stages:
  - version
  - 📦 docker
  - helm

version:
  stage: version
  script:
    - echo "export VERSION=$(git describe --tags --abbrev=0)" > $CI_PROJECT_DIR/variables
  artifacts:
    paths:
    - variables
  only:
    - tags

build-push-clean:
  stage: 📦 docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - source $CI_PROJECT_DIR/variables
  script:
    - /kaniko/executor
      --build-arg DISABLE_TENANT_SETTINGS='true'
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination "eu.gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$VERSION"
  only:
    - tags

helm:
  stage: helm
  script:
    - source $CI_PROJECT_DIR/variables
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/ubiquitypress/kubernetes kubernetes
    - helm init --client-only --skip-refresh
    - helm plugin install https://github.com/hypnoglow/helm-s3.git
    - helm repo add ubiquity s3://service-helm/charts
    - python3 kubernetes/ci/update_chart.py $IMAGE_NAME $IMAGE_NAME
    - helm package kubernetes/$IMAGE_NAME/helm/$IMAGE_NAME
    - helm s3 push --force /builds/ubiquitypress/$IMAGE_NAME/$IMAGE_NAME-$VERSION.tgz ubiquity
  only:
    - tags
