terms:
  - id: Abertay University
    term: Abertay University
    isni: 
    active: true
  - id: Aberystwyth University
    term: Aberystwyth University
    active: true
  - id: Anglia Ruskin University
    term: Anglia Ruskin University
    active: true
  - id: Aston University
    term: Aston University
    active: true
  - id: Bangor University
    term: Bangor University
    active: true
  - id: Bath Spa University
    term: Bath Spa University
    active: true
  - id: Birkbeck, University of London
    term: Birkbeck, University of London
    active: true
  - id: Birmingham City University
    term: Birmingham City University
    active: true
  - id: Bournemouth University
    term: Bournemouth University
    active: true
  - id: Brunel University
    term: Brunel University
    active: true
  - id: Bucks New University
    term: Bucks New University
    active: true
  - id: Cardiff Metropolitan University
    term: Cardiff Metropolitan University
    active: true
  - id: Cardiff University
    term: Cardiff University
    active: true
  - id: City, University of London
    term: City, University of London
    active: true
  - id: Courtauld Institute of Art
    term: Courtauld Institute of Art
    active: true
  - id: Coventry University
    term: Coventry University
    active: true
  - id: Cranfield University
    term: Cranfield University
    active: true
  - id: De Montfort University
    term: De Montfort University
    active: true
  - id: Durham University
    term: Durham University
    active: true
  - id: Edge Hill University
    term: Edge Hill University
    active: true
  - id: Edinburgh Napier University
    term: Edinburgh Napier University
    active: true
  - id: Falmouth University
    term: Falmouth University
    active: true
  - id: Glasgow Caledonian University
    term: Glasgow Caledonian University
    active: true
  - id: Glasgow School of Art
    term: Glasgow School of Art
    active: true
  - id: Goldsmiths, University of London
    term: Goldsmiths, University of London
    active: true
  - id: Guildhall School of Music and Drama
    term: Guildhall School of Music and Drama
    active: true
  - id: Harper Adams University
    term: Harper Adams University
    active: true
  - id: Heriot-Watt University
    term: Heriot-Watt University
    active: true
  - id: Imperial College London
    term: Imperial College London
    active: true
  - id: Institute of Advanced Legal Studies
    term: Institute of Advanced Legal Studies
    active: true
  - id: Institute of Cancer Research
    term: Institute of Cancer Research
    active: true
  - id: Institute of Commonwealth Studies
    term: Institute of Commonwealth Studies
    active: true
  - id: Institute of Historical Research
    term: Institute of Historical Research
    active: true
  - id: Keele University
    term: Keele University
    active: true
  - id: King's College London
    term: King's College London
    active: true
  - id: Kingston University
    term: Kingston University
    active: true
  - id: Lambeth Palace Library
    term: Lambeth Palace Library
    active: true
  - id: Lancaster University
    term: Lancaster University
    active: true
  - id: Leeds Beckett University
    term: Leeds Beckett University
    active: true
  - id: Liverpool John Moores University
    term: Liverpool John Moores University
    active: true
  - id: Liverpool School of Tropical Medicine
    term: Liverpool School of Tropical Medicine
    active: true
  - id: London Business School
    term: London Business School
    active: true
  - id: London Metropolitan University
    term: London Metropolitan University
    active: true
  - id: London School of Economics and Political Science
    term: London School of Economics and Political Science
    active: true
  - id: London School of Hygiene and Tropical Medicine
    term: London School of Hygiene and Tropical Medicine
    active: true
  - id: London South Bank University
    term: London South Bank University
    active: true
  - id: Loughborough University
    term: Loughborough University
    active: true
  - id: Manchester Metropolitan University
    term: Manchester Metropolitan University
    active: true
  - id: Middlesex University
    term: Middlesex University
    active: true
  - id: Newcastle University
    term: Newcastle University
    active: true
  - id: Northumbria University
    term: Northumbria University
    active: true
  - id: Nottingham Trent University
    term: Nottingham Trent University
    active: true
  - id: Open University
    term: Open University
    active: true
  - id: Oxford Brookes University
    term: Oxford Brookes University
    active: true
  - id: Oxford Centre for Mission Studies
    term: Oxford Centre for Mission Studies
    active: true
  - id: Queen Margaret University
    term: Queen Margaret University
    active: true
  - id: Queen Mary, University of London
    term: Queen Mary, University of London
    active: true
  - id: Queen's University Belfast
    term: Queen's University Belfast
    active: true
  - id: Ravensbourne University London
    term: Ravensbourne University London
    active: true
  - id: Regent's University London
    term: Regent's University London
    active: true
  - id: Robert Gordon University
    term: Robert Gordon University
    active: true
  - id: Roehampton University
    term: Roehampton University
    active: true
  - id: Royal Academy of Music
    term: Royal Academy of Music
    active: true
  - id: Royal Central School of Speech and Drama
    term: Royal Central School of Speech and Drama
    active: true
  - id: Royal College of Art
    term: Royal College of Art
    active: true
  - id: Royal College of Music
    term: Royal College of Music
    active: true
  - id: Royal Holloway, University of London
    term: Royal Holloway, University of London
    active: true
  - id: Royal Veterinary College, University of London
    term: Royal Veterinary College, University of London
    active: true
  - id: School of Advanced Study, University of London
    term: School of Advanced Study, University of London
    active: true
  - id: Sheffield Hallam University
    term: Sheffield Hallam University
    active: true
  - id: SOAS, University of London
    term: SOAS, University of London
    active: true
  - id: Solent University
    term: Solent University
    active: true
  - id: St George's, University of London
    term: St George's, University of London
    active: true
  - id: St Mary's University, Twickenham
    term: St Mary's University, Twickenham
    active: true
  - id: Staffordshire University
    term: Staffordshire University
    active: true
  - id: Swansea University
    term: Swansea University
    active: true
  - id: Tavistock and Portman NHS Foundation Trust
    term: Tavistock and Portman NHS Foundation Trust
    active: true
  - id: Teesside University
    term: Teesside University
    active: true
  - id: UCL Institute of Education
    term: UCL Institute of Education
    active: true
  - id: Ulster University
    term: Ulster University
    active: true
  - id: University College London
    term: University College London
    active: true
  - id: University of Aberdeen
    term: University of Aberdeen
    active: true
  - id: University of Bath
    term: University of Bath
    active: true
  - id: University of Bedfordshire
    term: University of Bedfordshire
    active: true
  - id: University of Birmingham
    term: University of Birmingham
    active: true
  - id: University of Bolton
    term: University of Bolton
    active: true
  - id: University of Bradford
    term: University of Bradford
    active: true
  - id: University of Brighton
    term: University of Brighton
    active: true
  - id: University of Bristol
    term: University of Bristol
    active: true
  - id: University of Buckingham
    term: University of Buckingham
    active: true
  - id: University of Cambridge
    term: University of Cambridge
    active: true
  - id: University of Central Lancashire
    term: University of Central Lancashire
    active: true
  - id: University of Chester
    term: University of Chester
    active: true
  - id: University of Chichester
    term: University of Chichester
    active: true
  - id: University of Cumbria
    term: University of Cumbria
    active: true
  - id: University of Derby
    term: University of Derby
    active: true
  - id: University of Dundee
    term: University of Dundee
    active: true
  - id: University of East Anglia
    term: University of East Anglia
    active: true
  - id: University of East London
    term: University of East London
    active: true
  - id: University of Edinburgh
    term: University of Edinburgh
    active: true
  - id: University of Essex
    term: University of Essex
    active: true
  - id: University of Exeter
    term: University of Exeter
    active: true
  - id: University of Glasgow
    term: University of Glasgow
    active: true
  - id: University of Gloucestershire
    term: University of Gloucestershire
    active: true
  - id: University of Greenwich
    term: University of Greenwich
    active: true
  - id: University of Hertfordshire
    term: University of Hertfordshire
    active: true
  - id: University of Huddersfield
    term: University of Huddersfield
    active: true
  - id: University of Hull
    term: University of Hull
    active: true
  - id: University of Kent
    term: University of Kent
    active: true
  - id: University of Leeds
    term: University of Leeds
    active: true
  - id: University of Leicester
    term: University of Leicester
    active: true
  - id: University of Lincoln
    term: University of Lincoln
    active: true
  - id: University of Liverpool
    term: University of Liverpool
    active: true
  - id: University of London
    term: University of London
    active: true
  - id: University of Manchester
    term: University of Manchester
    active: true
  - id: University of Northampton
    term: University of Northampton
    active: true
  - id: University of Nottingham
    term: University of Nottingham
    active: true
  - id: University of Oxford
    term: University of Oxford
    active: true
  - id: University of Plymouth
    term: University of Plymouth
    active: true
  - id: University of Portsmouth
    term: University of Portsmouth
    active: true
  - id: University of Reading
    term: University of Reading
    active: true
  - id: University of Roehampton
    term: University of Roehampton
    active: true
  - id: University of Salford
    term: University of Salford
    active: true
  - id: University of Sheffield
    term: University of Sheffield
    active: true
  - id: University of South Wales
    term: University of South Wales
    active: true
  - id: University of Southampton
    term: University of Southampton
    active: true
  - id: University of St Andrews
    term: University of St Andrews
    active: true
  - id: University of Stirling
    term: University of Stirling
    active: true
  - id: University of Strathclyde
    term: University of Strathclyde
    active: true
  - id: University of Sunderland
    term: University of Sunderland
    active: true
  - id: University of Surrey
    term: University of Surrey
    active: true
  - id: University of Sussex
    term: University of Sussex
    active: true
  - id: University of the Arts London
    term: University of the Arts London
    active: true
  - id: University of the Highlands & Islands
    term: University of the Highlands & Islands
    active: true
  - id: University of the West of England
    term: University of the West of England
    active: true
  - id: University of the West of Scotland
    term: University of the West of Scotland
    active: true
  - id: University of Wales, Trinity Saint David
    term: University of Wales, Trinity Saint David
    active: true
  - id: University of Warwick
    term: University of Warwick
    active: true
  - id: University of West London
    term: University of West London
    active: true
  - id: University of Westminster
    term: University of Westminster
    active: true
  - id: University of Winchester
    term: University of Winchester
    active: true
  - id: University of Wolverhampton
    term: University of Wolverhampton
    active: true
  - id: University of York
    term: University of York
    active: true
  - id: Warburg Institute
    term: Warburg Institute
    active: true
  - id: Wrexham Glyndwr University
    term: Wrexham Glyndwr University
    active: true
  - id: York St John University
    term: York St John University
    active: true
