terms:
- id: PhD
  term: PhD
  active: true
- id: DBA
  term: DBA
  active: true
- id: DClinPsy
  term: DClinPsy
  active: true
- id: DDS
  term: DDS
  active: true
- id: DEdPsy
  term: DEdPsy
  active: true
- id: DHRes
  term: DHRes
  active: true
- id: DLitt
  term: DLitt
  active: true
- id: DMin
  term: DMin
  active: true
- id: DPhil
  term: DPhil
  active: true
- id: DMus
  term: DMus
  active: true
- id: DPT
  term: DPT
  active: true
- id: DrPH
  term: DrPH
  active: true
- id: DSc
  term: DSc
  active: true
- id: DSocSci
  term: DSocSci
  active: true
- id: EdD
  term: EdD
  active: true
- id: EngD
  term: EngD
  active: true
- id: HScD
  term: HScD
  active: true
- id: MA
  term: MA
  active: true
- id: MD
  term: MD
  active: true
- id: MBA
  term: MBA
  active: true
- id: MLitt
  term: MLitt
  active: true
- id: MRes
  term: MRes
  active: true
- id: MSc
  term: MSc
  active: true
- id: MSt
  term: MSt
  active: true
- id: ProfDoc
  term: ProfDoc
  active: true
- id: ThD
  term: ThD
  active: true
