development:
  host: <%= ENV['REDIS_CACHE_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_CACHE_PORT'] || 6379 %>
test:
  host: <%= ENV['REDIS_CACHE_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_CACHE_PORT'] || 6379 %>
production:
  host: <%= ENV['REDIS_CACHE_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_CACHE_PORT'] || 6379 %>
